apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    resources: {}
    volumeMounts: 
    - name: myvolume 
      mountPath: /etc/foo 
  - args:
    - /bin/sh
    - -c
    - sleep 3600
    image: busybox
    name: busybox2 
    volumeMounts: 
    - name: myvolume 
      mountPath: /etc/foo 
  volumes: 
  - name: myvolume 
    emptyDir: {} 
