apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: apache
  name: apache
  namespace: kubespace
spec:
  containers:
  - image: httpd
    name: apache
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
