apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: job
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: job
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: job
            resources: {}
          restartPolicy: Never
  schedule: '* * * * *'
status: {}
