apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  volumes: 
  - name: myvolume 
    configMap:
      name: cmvolume 
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts: 
    - name: myvolume 
      mountPath: /etc/lala 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
