apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-22T04:26:15Z"
  name: nginx
  namespace: default
  resourceVersion: "97293"
  uid: 4843b558-2a9b-41e9-8b77-db78139a75cf
spec:
  clusterIP: 10.100.52.147
  clusterIPs:
  - 10.100.52.147
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort 
status:
  loadBalancer: {}
