apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        command: ["/bin/sh","-c"]
        args: ["sed -i 's/listen  .*/listen 6789;/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;' "]
        ports:
        - containerPort: 6789
        resources: {}
status: {}
