apiVersion: v1
kind: pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  serviceAccountName: myuser
  containers:
  - image: nginx:latest
    name: nginx
    command: ["/bin/sh","-c"]
    args: ["sed -i 's/listen  .*/listen 6789;/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
    ports:
    - containerPort: 6789
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
