apiVersion: v1
kind: PersistentVolume
metadata:
        name: mypv
spec:
    accessModes:
         - ReadWriteOnce
         - ReadWriteMany
    storageClassName: normal
    capacity:
            storage: 10Gi
    hostPath:
            path: /etc/foo 
